on:
  push:
    branches:
      - 'main'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print to log
        run: echo "hello log"
      - name: Create branch
        run: git switch -c "pr-branch"
      - name: Make change
        run: echo "test">>hello-world.py
      - name: add change
        run: git add .
      - name: commit change
        run: git commit -m "dummy change"
      - name: Create pr
        run: gh pr create --title "test pr from gh" --body "Could this work?" --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
