on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to log
        run: |
          echo "hello log ${RANDOM}"
          somevar="text_with_random_${RANDOM}"
          echo "print somevar $somevar or ${somevar}"
          somecmd=$(id)
          echo "print somecmd $somecmd"
