on:
  push:
    branches:
      - 'main'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print to log
        run: echo "hello log"
      - name: fetch
        run: git fetch
      - name: Create branch
        run: git switch -c "pr-branch2"
      - name: cherry-pick
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git cherry-pick "d043685e852bd86b0d75e880ce2625f54a404bc1"
          git push --set-upstream origin pr-branch2
      - name: Create pr
        run: gh pr create --title "test pr from gh" --body "Could this work?" --base main --repo madelen-at-work/action-tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
