on:
  push:
    branches:
      - 'main'

jobs:
  do-da-pr:
    runs-on: ubuntu-latest
    steps:
      - name: clone 2nd repo
        run: |
          git clone https://madelen-at-work/action-tester2
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git switch -c "pr-branch"
          git remote add other https://madelen-at-work/action-teser
          git fetch other
      - name: cherry-pick
        run: |
          git cherry-pick "d043685e852bd86b0d75e880ce2625f54a404bc1"
          git push --set-upstream origin pr-branch
      - name: Create pr
        run: gh pr create --title "test pr from gh" --body "Could this work?" --base main --repo madelen-at-work/action-tester2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
