on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/trigger.yml'

jobs:
  send-dispatch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to 2nd repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $BEARER_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/madelen-at-work/action-tester2/actions/workflows/reaction.yml/dispatches \
          -d '{"ref":"main"}'
        env:
          BEARER_TOKEN: ${{ secrets.WORKFLOWDISPATCHPAT }}
